---
- hosts: testrunner
  tasks:
    # from https://docs.docker.com/engine/install/centos/
    - name: Ensure group "docker" exists
      become: yes
      group:
        name: docker
        state: present

    - name: Remove conflicting packages
      become: yes
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Enable docker-ce repo
      become: yes
      command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

    - name: Install needed packages
      become: yes
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - python-requests
        state: present

    - name: Set SELinux in permissive mode
      become: yes
      selinux:
        state: permissive
        policy: targeted

    - name: Start the docker service
      become: yes
      service:
        name: docker
        state: started

    - name: Check docker service
      become: yes
      command: "systemctl status docker"

    - name: Add user zuul-worker to the docker group
      become: yes
      user:
        name: 'zuul-worker'
        groups: 'docker'
        append: 'yes'
